baseURL = "https://blog.seraf.dev/voyagetaiba"
title = "Voyage Taiba"

languageCode = "en-us"
DefaultContentLanguage = "en"

enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true
canonifyURLs = true
paginate = 9
darkmode_js = ["assets/js/darkmode.js"]
enableInlineShortcodes = true

[params]
author = "Youssef Karroum"
authorimage = "../assets/images/global/logo.png"
facebook = "https://facebook.com/voyagetaiba"
og_image = "../assets/images/global/logo.png"
sitename = "Voyage Taiba"
twitter = "@voyagetaiba"
description = "Agence de Voyage Taiba"

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[taxonomies]
category = "Categories"
tag = "Tags"

[privacy]
[privacy.disqus]
disable = false
[privacy.googleAnalytics]
anonymizeIP = true
disable = false
respectDoNotTrack = false
useSessionStorage = false
[privacy.instagram]
disable = false
simple = false
[privacy.twitter]
disable = false
enableDNT = false
simple = false
[privacy.vimeo]
disable = false
enableDNT = false
simple = false
[privacy.youtube]
disable = false
privacyEnhanced = true

[module]
[module.hugoVersion]
extended = true
min = "0.104.0"
