const defaultTheme = require("tailwindcss/defaultTheme");

// tailwind.config.js
module.exports = {
    content: ["./layouts/**/*.html", "./content/**/*.md"],
    darkMode: "class",
    theme: {
        extend: {
            colors: {
                transparent: "transparent",
                current: "currentColor",
                primary: {
                    DEFAULT: "#6366F1",
                    50: "#FFFFFF",
                    100: "#F9F9FE",
                    200: "#D3D4FB",
                    300: "#AEAFF8",
                    400: "#888BF4",
                    500: "#6366F1",
                    600: "#3034EC",
                    700: "#1317D1",
                    800: "#0E119E",
                    900: "#0A0C6A",
                },
                secondary: {
                    DEFAULT: "#EC4899",
                    50: "#FDEEF6",
                    100: "#FBDCEB",
                    200: "#F8B7D7",
                    300: "#F492C2",
                    400: "#F06DAE",
                    500: "#EC4899",
                    600: "#E4187D",
                    700: "#B11261",
                    800: "#7F0D45",
                    900: "#4C0829",
                },
                neutral: {
                    DEFAULT: "#6B7280",
                    50: "#CDD0D5",
                    100: "#C2C5CC",
                    200: "#ACB0BA",
                    300: "#969BA7",
                    400: "#7F8694",
                    500: "#6B7280",
                    600: "#515761",
                    700: "#383C43",
                    800: "#1E2024",
                    900: "#050506",
                },
                CUSTOM_GREEN_BLUE: {
                    DEFAULT: "#116173",
                    50: "#56CBE6",
                    100: "#44C6E3",
                    200: "#21BBDE",
                    300: "#1C9DBA",
                    400: "#167F97",
                    500: "#116173",
                    600: "#0A3842",
                    700: "#030F11",
                    800: "#000000",
                    900: "#000000",
                    950: "#000000",
                },
                CUSTOM_GREY: {
                    DEFAULT: "#BFBFBF",
                    50: "#FFFFFF",
                    100: "#FFFFFF",
                    200: "#FCFCFC",
                    300: "#E8E8E8",
                    400: "#D3D3D3",
                    500: "#BFBFBF",
                    600: "#A3A3A3",
                    700: "#878787",
                    800: "#6B6B6B",
                    900: "#4F4F4F",
                    950: "#414141",
                },
                CUSTOM_YELLOW: {
                    DEFAULT: "#FFBB19",
                    50: "#FFF1D1",
                    100: "#FFEBBC",
                    200: "#FFDF93",
                    300: "#FFD36B",
                    400: "#FFC742",
                    500: "#FFBB19",
                    600: "#E09E00",
                    700: "#A87600",
                    800: "#704F00",
                    900: "#382700",
                    950: "#1C1300",
                },
                CUSTOM_RED_PRICE_COLOR: {
                    DEFAULT: "#C01616",
                    50: "#F39A9A",
                    100: "#F18888",
                    200: "#ED6363",
                    300: "#E93F3F",
                    400: "#E51A1A",
                    500: "#C01616",
                    600: "#8E1010",
                    700: "#5B0A0A",
                    800: "#290505",
                    900: "#000000",
                    950: "#000000",
                },
                // To change these, use https://www.tailwindshades.com/ with https://tailwindcss.com/docs/customizing-colors or create your own custom colors.

                // First color that sheikh yussuf : #115F61
                // second color is : #BFBFBF
                // and the buttons and little details in this :  #FFBB19
                // and last color he gave me is : C01616 for the prices
            },
            lineHeight: {
                "extra-loose": "2.5",
                12: "3rem",
            },
            typography: (theme) => ({
                DEFAULT: {
                    css: {
                        "--tw-prose-body": theme("colors.zinc[800]"),
                        "--tw-prose-headings": theme("colors.zinc[900]"),
                        "--tw-prose-lead": theme("colors.zinc[700]"),
                        "--tw-prose-links": theme("colors.zinc[900]"),
                        "--tw-prose-bold": theme("colors.zinc[900]"),
                        "--tw-prose-counters": theme("colors.zinc[600]"),
                        "--tw-prose-bullets": theme("colors.zinc[400]"),
                        "--tw-prose-hr": theme("colors.zinc[300]"),
                        "--tw-prose-quotes": theme("colors.zinc[900]"),
                        "--tw-prose-quote-borders": theme("colors.zinc[300]"),
                        "--tw-prose-captions": theme("colors.zinc[700]"),
                        "--tw-prose-code": theme("colors.indigo[500]"),
                        "--tw-prose-pre-code": theme("colors.indigo[300]"),
                        "--tw-prose-pre-bg": theme("colors.gray[900]"),
                        "--tw-prose-th-borders": theme("colors.zinc[300]"),
                        "--tw-prose-td-borders": theme("colors.zinc[200]"),
                        "--tw-prose-invert-body": theme("colors.zinc[200]"),
                        "--tw-prose-invert-headings": theme("colors.white"),
                        "--tw-prose-invert-lead": theme("colors.zinc[300]"),
                        "--tw-prose-invert-links": theme("colors.indigo[400]"),
                        "--tw-prose-invert-bold": theme("colors.white"),
                        "--tw-prose-invert-counters": theme("colors.zinc[400]"),
                        "--tw-prose-invert-bullets": theme("colors.zinc[200]"),
                        "--tw-prose-invert-hr": theme("colors.zinc[500]"),
                        "--tw-prose-invert-quotes": theme("colors.zinc[100]"),
                        "--tw-prose-invert-quote-borders":
                            theme("colors.zinc[700]"),
                        "--tw-prose-invert-captions": theme("colors.zinc[400]"),
                        "--tw-prose-invert-code": theme("colors.indigo[400]"),
                        "--tw-prose-invert-pre-code":
                            theme("colors.indigo[300]"),
                        "--tw-prose-invert-pre-bg": theme("colors.gray[900]"),
                        "--tw-prose-invert-th-borders":
                            theme("colors.zinc[100]"),
                        "--tw-prose-invert-td-borders":
                            theme("colors.zinc[500]"),
                    },
                },
            }),
        },
    },
    variants: {
        typography: ["light"],
    },
    plugins: [require("@tailwindcss/typography")],
};
